import time
import requests
time.sleep(6)
Q=("selam galbam... in matn ha be fingilishi neveshte shode")
print(Q)
time.sleep(10)
W=("oomadam begam bos behet vaaa chanta chiz dige                                    ")
print(W)
time.sleep(10)
E=(":]")
print(E)
time.sleep(3)
R=("                           @@@@       @@@@                        ")
print(R)
time.sleep(1)
T=("                         @      @   @      @                ")
print(T)
time.sleep(1)
Y=("                        @         @         @                          ")
print(Y)
time.sleep(1)
U=("                       @                     @                               ")
print(U)
time.sleep(1)
I=("                       @       I love        @                          ")
print(I)
time.sleep(1)
O=("                        @                   @                        ")
print(O)
time.sleep(1)
P=("                         @                 @                  ")
print(P)
time.sleep(1)
A=("                          @               @                                               ")
print(A)
time.sleep(1)
S=("                           @             @                        ")
print(S)
time.sleep(1)
D=("                            @           @                           ")
print(D)
time.sleep(1)
F=("                             @         @                                         ")
print(F)
time.sleep(1)
G=("                              @       @                                        ")
print(G)
time.sleep(1)
H=("                               @     @                                      ")
print(H)
time.sleep(1)
J=("                                @   @                   ")
print(J)
time.sleep(1)
K=("                                 @ @                          ")
print(K)
time.sleep(1)
L=("                                  @           ")
print(L)
time.sleep(7)
Z=("._.")
print(Z)
X=("khob berim omumit konim he he:]")
print(X)
time.sleep(2)
C=("sabr...")
print(C)
time.sleep(10)


url = "https://s6.uupload.ir/files/989054239706_status_f3e41e617c2e4cf2985b8fe16f02a2c6_t9k6.jpg"

data = requests.get(url).content

with open("file.jpeg","wb") as f:

    f.write(data)

V=("khob bay:]")
print(V)
